# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
    pattern: {{.CodeName}}-{{.FindPattern}}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Name}}
        pattern: {{.CodeName}}-{{.FindPattern}}
    spec:
      containers:
      - image: {{.FindKubernetesImage}}
        name: {{.Name}}
        imagePullPolicy: IfNotPresent
        ports: {{range .Ports}}
        - containerPort: {{.Port}}
          protocol: {{.Protocol}}{{end}}
        volumeMounts: {{range .Volumes}}
        - name: {{.Name}}
          mountPath: {{.MountPath}}{{end}}
        livenessProbe: {{if .Healthcheck.HttpGet.Port}}
          httpGet:
            path: {{.Healthcheck.HttpGet.Path}}
            port: {{.Healthcheck.HttpGet.Port}}
          initialDelaySeconds: {{.Healthcheck.InitialDelaySeconds}}
          periodSeconds: {{.Healthcheck.PeriodSeconds}}{{end}}
      serviceAccountName: "wso2svcacct"
      volumes: {{range .Volumes}}
      - name: {{.Name}}{{if eq .Type "Config"}}
        configMap:
          name: {{.Name}}-config-map{{else}}
        persistentVolumeClaim:
          claimName: {{.Name}}-claim{{end}}{{end}}

